version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile  # Dockerfile'ın doğru yolu
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ticket-system
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app


#websoketle refresh restful apide ssl verify =false header, except application
#pop up exception handling için çıkart

